apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: skiapp
  template:
    metadata:
      labels:
        app: skiapp
    spec:
      containers:
      - image: sharepointoscar/skiapp:b3fa0e081c3ea4c5c6e46d038bc88e45a12dcc2e
        name: skiapp
        ports:
        - containerPort: 8080
