# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: skiapp
# spec:
#   replicas: 2
#   revisionHistoryLimit: 3
#   selector:
#     matchLabels:
#       app: skiapp
#   template:
#     metadata:
#       labels:
#         app: skiapp
#     spec:
#       containers:
#       - image: sharepointoscar/skiapp:v1
#         name: skiapp
#         ports:
#         - containerPort: 8080
