apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riker-ingress
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:540060600283:certificate/36af44f2-e376-479f-9ef0-834ab69ecf88"
spec:
  rules:
  - host: guestbook-ui.{{ .Values.spec.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui
            port: 
              number: 80
        
        