apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riker-ingress
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: guestbook-ui.{{ .Values.spec.ingress.host }}
    http:
      paths:
      - path: /skiapp
        pathType: Prefix
        backend:
          service:
            name: skiapp
            port: 
              number: 80
        
        