apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skiapp-ingress
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: guestbook-ui.{{ .Values.spec.ingress.host }}
    http:
      paths:
      - path: /skiapp
        pathType: Prefix
        backend:
          service:
            name: skiapp-service
            port: 
              number: 8080
        
        