apiVersion: v1
kind: Service
metadata:
  name: ngnix-skiapp-service
  namespace: team-riker
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: ngnix-skiapp
