apiVersion: v1
kind: Service
metadata:
  name: skiapp-service-preview
  namespace: team-riker-space
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: skiapp